# Generated by Django 4.0.5 on 2022-07-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='review',
            new_name='Feedback',
        ),
    ]
