# Generated by Django 4.0.5 on 2022-07-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_review_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress1', models.CharField(max_length=500)),
                ('adress2', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
