# Generated by Django 4.0.5 on 2022-07-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='adress1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='adress2',
            new_name='address2',
        ),
    ]
